DROP TABLE EDIT_TOOLS_LIST;

DROP TABLE VIDEO_LINKS;

DROP TABLE APPLY_EDITOR;

DROP TABLE EDIT_CAREER;

DROP TABLE EDITOR_REVIEW;

DROP TABLE CHANNEL_CATEGORY;

DROP TABLE RECRUIT_BOARD;

DROP TABLE REVENUE_MANAGE;

DROP TABLE YOUTUBER_REVIEW;

DROP TABLE PORTFOLIO;

DROP TABLE QNA;

DROP TABLE CASH_HISTORY;

DROP TABLE REVIEWABLE_MEMBER;

DROP TABLE USER_EDITOR;

DROP TABLE USER_YOUTUBER;

DROP TABLE USER_INFO;


CREATE TABLE USER_INFO (
	ID 				VARCHAR2(30) 						CONSTRAINT USER_INFO_ID_PK 				PRIMARY KEY
, 	PASSWORD 		VARCHAR2(20)						CONSTRAINT USER_INFO_PASSWORD_NN 		NOT NULL
, 	NAME 			VARCHAR2(15) 						CONSTRAINT USER_INFO_NAME_NN 			NOT NULL
, 	NICKNAME 		VARCHAR2(30) 						CONSTRAINT USER_INFO_NICKNAME_NN 		NOT NULL
, 	PHONE_NUMBER 	VARCHAR2(150) 						CONSTRAINT USER_INFO_PHONE_NUMBER_NN 	NOT NULL
, 	ADDRESS 		VARCHAR2(150) 						CONSTRAINT USER_INFO_ADDRESS_NN 		NOT NULL
, 	DETAIL_ADDR 	VARCHAR2(150) 						CONSTRAINT USER_INFO_DETAIL_ADDR_NN 	NOT NULL
, 	USER_TYPE 		VARCHAR2(9) 						CONSTRAINT USER_INFO_USER_TYPE_NN 		NOT NULL
, 	GENDER 			VARCHAR2(3) 						CONSTRAINT USER_INFO_GENDER_NN 			NOT NULL
, 	EMAIL_AGREE 	VARCHAR2(5) 						CONSTRAINT USER_INFO_EMAIL_AGREE_NN 	NOT NULL
, 	SMS_AGREE 		VARCHAR2(5) 						CONSTRAINT USER_INFO_SMS_AGREE_NN 		NOT NULL
, 	BIRTH_DATE 		DATE 								CONSTRAINT USER_INFO_DATE_NN 			NOT NULL
, 	REGISTER_DATE  	DATE 			DEFAULT SYSDATE 	CONSTRAINT USER_INFO_REGISTER_DATE_NN 	NOT NULL
, 	REVIEW_AUTH 	VARCHAR2(5) 	DEFAULT 'FALSE' 	CONSTRAINT USER_INFO_REVIEW_AUTH_NN 	NOT NULL
, 	RED_CARD 		VARCHAR2(5) 	DEFAULT 'FALSE' 	CONSTRAINT USER_INFO_RED_CARD_NN 		NOT NULL
, 	CASH_BALANCE 	NUMBER(10) 		DEFAULT 0 			CONSTRAINT USER_INFO_CASH_BALANCE_NN 	NOT NULL
, 	YELLOW_CARD 	NUMBER(1) 		DEFAULT 0 			CONSTRAINT USER_INFO_YELLOW_CARD_NN 	NOT NULL
, 	PROFILE_PHOTO 	VARCHAR2(100) 	DEFAULT '' 			CONSTRAINT USER_INFO_PROFILE_PHOTO_NN 	NOT NULL
, 	CONSTRAINT 		USER_INFO_NICKNAME_UQ 		UNIQUE (NICKNAME)
, 	CONSTRAINT 		USER_INFO_USER_TYPE_CK 		CHECK (USER_TYPE IN ('유튜버', '편집자'))
, 	CONSTRAINT 		USER_INFO_GENDER_CK 		CHECK (GENDER IN ('남', '여'))
, 	CONSTRAINT 		USER_INFO_EMAIL_AGREE_CK 	CHECK (EMAIL_AGREE IN ('TRUE', 'FALSE'))
, 	CONSTRAINT 		USER_INFO_SMS_AGREE_CK 		CHECK (SMS_AGREE IN ('TRUE', 'FALSE'))
, 	CONSTRAINT 		USER_INFO_REVIEW_AUTH_CK 	CHECK (REVIEW_AUTH IN ('TRUE', 'FALSE'))
, 	CONSTRAINT 		USER_INFO_YELLOW_CARD_CK 	CHECK (YELLOW_CARD BETWEEN 0 AND 3)
, 	CONSTRAINT 		USER_INFO_RED_CARD_CK 		CHECK (RED_CARD IN ('TRUE', 'FALSE'))
);

CREATE TABLE REVIEWABLE_MEMBER (
 	ID 				VARCHAR2(20) 					CONSTRAINT REVIEWABLE_ID_PK 				PRIMARY KEY
,	ACQUIRED_PATH 	VARCHAR2(13) 					CONSTRAINT REVIEWABLE_ACQUIRED_PATH_NN 		NOT NULL
,	AUTH_DATE 		DATE 			DEFAULT SYSDATE CONSTRAINT REVIEWABLE_MEMBER_AUTH_DATE_NN 	NOT NULL
,	CONSTRAINT 		REVIEWABLE_MEMBER_ID_FK 	FOREIGN KEY (ID) REFERENCES USER_INFO (ID)
,	CONSTRAINT 		REVIEWABLE_MEMBER_PATH_PK 	CHECK (ACQUIRED_PATH IN('멤버십','리뷰작성'))
);

CREATE TABLE CASH_HISTORY (
	CASH_NO 		NUMBER(7) 	 							CONSTRAINT CASH_HISTORY_CASH_NO_PK 		PRIMARY KEY
,	AMOUNT 			NUMBER(7)	 							CONSTRAINT CASH_HISTORY_AMOUNT_NN		NOT NULL
,	ID 				VARCHAR2(30) 							CONSTRAINT CASH_HISTORY_ID_NN 			NOT NULL
,	USE_DETAIL 		VARCHAR2(25) 							CONSTRAINT CASH_HISTORY_USE_DETALE_NN 	NOT NULL
,	USE_DATE 		DATE	 			DEFAULT SYSDATE 	CONSTRAINT CASH_HISTORY_USE_DATE_NN 	NOT NULL 
,	CONSTRAINT 	 	CASH_HISTORY_ID_FK 	FOREIGN KEY (ID) 	REFERENCES USER_INFO (ID)
);

CREATE TABLE QNA (
	QNA_NO 			NUMBER(7) 							CONSTRAINT QNA_NO_PK 		PRIMARY KEY
,	NICKNAME 		VARCHAR2(30) 						CONSTRAINT QNA_NICKNAME_NN 	NOT NULL
,	QUESTION 		VARCHAR2(1000) 						CONSTRAINT QNA_QEUSTION_NN 	NOT NULL
,	SECURITY 		VARCHAR2(5) 		DEFAULT 'FALSE' CONSTRAINT QNA_SECURITY_NN 	NOT NULL
,	ANSWER 			VARCHAR2(1000) 		DEFAULT '' 		CONSTRAINT QNA_ANSWER_NN 	NOT NULL
,	CONSTRAINT 		QNA_NICKNAME_FK 	FOREIGN KEY (NICKNAME) 	REFERENCES USER_INFO (NICKNAME)
,	CONSTRAINT 		QNA_SECURITY_CK 	CHECK(SECURITY IN('TRUE','FALSE'))
);

CREATE TABLE USER_YOUTUBER (
	YOUTUBER_ID 	VARCHAR2(30) 	CONSTRAINT USER_YOUTUBER_ID_FK REFERENCES USER_INFO (ID)
, 	CHANNEL_ID 		VARCHAR2(30) 	CONSTRAINT USER_YOUTUBER_CHANNEL_ID_NN NOT NULL
, 	CONSTRAINT 		USER_YOUTUBER_ID_PK 			PRIMARY KEY (YOUTUBER_ID)
,	CONSTRAINT 		USER_YOUTUBER_CHANNEL_ID_UQ 	UNIQUE (CHANNEL_ID)
);


CREATE TABLE USER_EDITOR (
 	EDITOR_ID 		VARCHAR2(30) 								CONSTRAINT USER_EDITOR_ID_FK REFERENCES USER_INFO(ID)
, 	IS_UPLOADED 	VARCHAR2(5) 				DEFAULT 'FALSE' CONSTRAINT USER_EDITOR_IS_UPLOADED_NN NOT NULL
, 	CONSTRAINT 		USER_EDITOR_ID_PK 			PRIMARY KEY (EDITOR_ID)
, 	CONSTRAINT 		USER_EDITOR_IS_UPLOADED_CK 	CHECK(IS_UPLOADED IN('TRUE','FALSE'))
);

CREATE TABLE YOUTUBER_REVIEW(
	YOUTUBER_REVIEW_NO 	NUMBER(7) 							CONSTRAINT YOUTUBER_REVIEW_NO_PK 			PRIMARY KEY
,	CHANNEL_ID 			VARCHAR2(20) 						CONSTRAINT YOUTUBER_REVIEW_CHANNEL_ID_NN 	NOT NULL
,	EDITOR_ID	 		VARCHAR2(30) 						CONSTRAINT YOUTUBER_REVIEW_ID_NN 			NOT NULL 
,	REVIEW_COMMENT 		VARCHAR2(1000) 						CONSTRAINT YOUTUBER_REVIEW_COMMENT_NN 		NOT NULL
, 	REVIEW_POSITIVE 	VARCHAR2(1000) 						CONSTRAINT YOUTUBER_REVIEW_POSITIVE_NN 		NOT NULL
, 	REVIEW_NEGATIVE 	VARCHAR2(1000) 						CONSTRAINT YOUTUBER_REVIEW_NEGATIVE_NN 		NOT NULL
,	RATINGS 			NUMBER(1) 							CONSTRAINT YOUTUBER_REVIEW_RATINGS_NN 		NOT NULL
,	REPORTS 			NUMBER(1) 		DEFAULT 0 			CONSTRAINT YOUTUBER_REVIEW_REPORTS_NN 		NOT NULL
,	IS_PUBLIC 			VARCHAR2(5) 	DEFAULT 'TRUE' 		CONSTRAINT YOUTUBER_REVIEW_IS_PUBLIC_NN 	NOT NULL
,	CONSTRAINT 		EDITOR_REVIEW_CHANNEL_ID_FK FOREIGN KEY (CHANNEL_ID) 	REFERENCES USER_YOUTUBER(CHANNEL_ID)
,	CONSTRAINT 		EDITOR_REVIEW_ID_FK 		FOREIGN KEY (EDITOR_ID) 	REFERENCES USER_EDITOR(EDITOR_ID)
);


CREATE TABLE REVENUE_MANAGE (
	REVENUE_NO 			NUMBER(7) 							CONSTRAINT REVENUE_MANAGE_NO_NN 		PRIMARY KEY
, 	REVENUE_CASH 		NUMBER(7)							CONSTRAINT REVENUE_MANAGE_CASH_NN 		NOT NULL
, 	REVENUE_DETAIL 		VARCHAR2(25) 						CONSTRAINT REVENUE_MANAGE_DETALE_NN 	NOT NULL
, 	REVENUE_DATE 		DATE 			DEFAULT SYSDATE 	CONSTRAINT REVENUE_MANAGE_DATE_NN 		NOT NULL
, 	CONSTRAINT 			REVENUE_MANAGE_DETAIL 	CHECK (REVENUE_DETAIL IN ('구인글 등록 비용','회원권 판매 수익','광고 수익'))
);

CREATE TABLE RECRUIT_BOARD (
 	RECRUIT_NO 			NUMBER(7) 								CONSTRAINT RECRUIT_BOARD_NO_PK 				PRIMARY KEY
, 	YOUTUBER_ID 		VARCHAR2(30) 							CONSTRAINT RECRUIT_BOARD_YOUTUBER_ID_FK 	REFERENCES USER_YOUTUBER (YOUTUBER_ID)
, 	TEMPORARY_SAVE 		VARCHAR2(5) 							CONSTRAINT RECRUIT_SAVE_NN 					NOT NULL
, 	RECRUIT_TITLE 		VARCHAR2(20) 	DEFAULT '' 				CONSTRAINT RECRUIT_TITLE_NN 				NOT NULL
, 	DUTY 				VARCHAR2(300) 	DEFAULT '' 				CONSTRAINT RECRUIT_DUTY_NN 					NOT NULL
, 	WORKLOAD 			VARCHAR2(300) 	DEFAULT '' 				CONSTRAINT RECRUIT_WORKLOAD_NN 				NOT NULL
, 	REQUIREMENT 		VARCHAR2(1000) 	DEFAULT '' 				CONSTRAINT RECRUIT_REQUIREMENT_NN			NOT NULL
, 	SALARY_DETAIL 		VARCHAR2(300) 	DEFAULT '내용 없음' 	 CONSTRAINT RECRUIT_SAL_DETAIL_NN 			 NOT NULL
, 	PREFERENCE 			VARCHAR2(300) 	DEFAULT '' 				CONSTRAINT RECRUIT_PREFERENCE_NN 			NOT NULL
, 	EDIT_TOOLS 			VARCHAR2(300) 	DEFAULT '' 				CONSTRAINT RECRUIT_EDIT_TOOLS_NN 			NOT NULL
, 	ENVIRONMENT 		VARCHAR2(300) 	DEFAULT '' 				CONSTRAINT RECRUIT_ENVIRONMENT_NN 			NOT NULL
, 	WELFARE 			VARCHAR2(500) 	DEFAULT '' 				CONSTRAINT RECRUIT_WELFARE_NN 				NOT NULL
, 	RECRUIT_DETAIL 		VARCHAR2(3000) 	DEFAULT '' 				CONSTRAINT RECRUIT_DETALE_NN 				NOT NULL
, 	IS_PUBLIC 			VARCHAR2(5) 	DEFAULT 'TRUE' 			CONSTRAINT RECRUIT_IS_PUBLIC_NN 			NOT NULL
, 	REPORTS 			NUMBER(1) 		DEFAULT 0 				CONSTRAINT RECRUIT_REPORTS_NN 				NOT NULL
, 	SALARY 				NUMBER(10) 		DEFAULT '' 				CONSTRAINT RECRUIT_SALARY_NN 				NOT NULL
, 	DEADLINE 			DATE 			DEFAULT SYSDATE 		CONSTRAINT RECRUIT_DEADLINE_NN 				NOT NULL
, 	CONSTRAINT 			RECRUIT_BOARD_REPORTS_CK 		CHECK(REPORTS BETWEEN 0 AND 3)
, 	CONSTRAINT 			RECRUIT_BOARD_IS_PUBLIC_CK 		CHECK(IS_PUBLIC IN('TRUE','FALSE'))
, 	CONSTRAINT 			RECRUIT_BOARD_SAVE_CK 			CHECK(TEMPORARY_SAVE IN ('TRUE','FALSE'))
); 

CREATE TABLE CHANNEL_CATEGORY (
	CATEGORY_NO 	NUMBER(7) 						CONSTRAINT CHANNEL_CATEGORY_NO_PK 	PRIMARY KEY
,	RECRUIT_NO 		NUMBER(7) 						CONSTRAINT CATEGORY_RECRUIT_NO_FK 	REFERENCES RECRUIT_BOARD(RECRUIT_NO)
,	CATEGORY 		VARCHAR2(30)	DEFAULT '기타' 	CONSTRAINT CATEGORY_NN 				NOT NULL
,	ETC_DETAILS 	VARCHAR2(30) 	DEFAULT '없음' 	CONSTRAINT CATEGORY_ETC_DETAILS 	NOT NULL
,	CONSTRAINT 		CATEGORY_CK 	CHECK(CATEGORY IN('먹방','게임','일상','요리','음악','영화','스포츠','학습','소통','자동차','IT','이슈','동물','기타'))
);

CREATE TABLE PORTFOLIO (
	EDITOR_ID 			VARCHAR2(30) 					CONSTRAINT 	PORTFOLIO_ID_FK 			REFERENCES 	USER_EDITOR (EDITOR_ID)
,	IS_PUBLIC 			VARCHAR(5) 						CONSTRAINT 	PORTFOLIO_IS_PUBLIC_NN 		NOT NULL
,	TEMPORARY_SAVE 		VARCHAR2(5) 					CONSTRAINT 	PORTFOLIO_TEMPORARYSAVE_NN 	NOT NULL
,	WORKABLE_LOCATION 	VARCHAR(100) 	DEFAULT '' 		CONSTRAINT PORTFOLIO_LOCATION_NN 		NOT NULL
,	TOTAL_VIDEO_TIME 	VARCHAR2(10) 	DEFAULT '' 		CONSTRAINT PORTFOLIO_TOTAL_VIDEO_NN 	NOT NULL
,	EDITE_TOOLS 		VARCHAR2(100) 	DEFAULT '' 		CONSTRAINT PORTFOLIO_EDITE_TOOLS_NN 	NOT NULL
,	OTHER_CAREER 		VARCHAR2(1000) 	DEFAULT '' 		CONSTRAINT PORTFOLIO_CAREER_NN			NOT NULL
,	MESSAGE 			VARCHAR2(3000) 	DEFAULT '' 		CONSTRAINT PORTFOLIO_MESSAGE_NN 		NOT NULL
,	PORTFOLIO_TITLE 	VARCHAR2(30) 	DEFAULT ''		CONSTRAINT PORTFOLIO_TITLE_NN 			NOT NULL
,	POST_DATE 			DATE 			DEFAULT SYSDATE CONSTRAINT PORTFOLIO_POST_DATE_NN		NOT NULL
,	CONSTRAINT 	PORTFOLIO_ID_PK 				PRIMARY KEY (EDITOR_ID)
,	CONSTRAINT 	PORTFOLIO_IS_PUBLIC_CK 			CHECK(IS_PUBLIC IN('TRUE','FALSE'))
,	CONSTRAINT 	PORTFIOLIO_TEMPORARY_SAVE_CK 	CHECK(TEMPORARY_SAVE IN('TRUE','FALSE'))
);

CREATE TABLE EDITOR_REVIEW(
 	VIDEO_REVIEW_NO 	NUMBER(7) 						CONSTRAINT VIDEO_REVIEW_NO_PK 			PRIMARY KEY
, 	EDITOR_ID 			VARCHAR2(30)					CONSTRAINT EDITOR_REVIEW_EDITOR_ID_NN 	NOT NULL
, 	YOUTUBER_ID 		VARCHAR2(30)					CONSTRAINT EDITOR_REVIEW_ID_NN 			NOT NULL
, 	REVIEW_COMMENT 		VARCHAR2(1000) 					CONSTRAINT EDITOR_REVIEW_COMMENT_NN 	NOT NULL
,  	REVIEW_POSITIVE 	VARCHAR2(1000) 					CONSTRAINT EDITOR_REVIEW_POSITIVE_NN 	NOT NULL
,  	REVIEW_NEGATIVE 	VARCHAR2(1000) 					CONSTRAINT EDITOR_REVIEW_NEGATIVE_NN 	NOT NULL
, 	RATINGS 			NUMBER(1)						CONSTRAINT EDITOR_REVIEW_RATINGS_NN 	NOT NULL
, 	REPORTS 			NUMBER(1)		DEFAULT 0 		CONSTRAINT EDITOR_REVIEW_REPORTS_NN  	NOT NULL
, 	IS_PUBLIC 			VARCHAR2(5)		DEFAULT 'TRUE'	CONSTRAINT EDITOR_REVIEW_IS_PUBLIC_NN 	NOT NULL
, 	CONSTRAINT EDITOR_REVIEW_EDITOR_ID_FK 	FOREIGN KEY(EDITOR_ID) 		REFERENCES USER_EDITOR(EDITOR_ID)
, 	CONSTRAINT EDITOR_REVIEW_NICKNAME_FK 	FOREIGN KEY(YOUTUBER_ID) 	REFERENCES USER_YOUTUBER(YOUTUBER_ID)
, 	CONSTRAINT EDITOR_REVIEW_RATINGS_CK 	CHECK(RATINGS BETWEEN 0 AND 5)
,  	CONSTRAINT EDITOR_REVIEW_REPORTS_CK  	CHECK(REPORTS BETWEEN 0 AND 3)
, 	CONSTRAINT EDITOR_REVIEW_IS_PUBLIC_CK  	CHECK(IS_PUBLIC IN('TRUE','FALSE'))
);

CREATE TABLE EDIT_CAREER (
 	CAREER_NO 		NUMBER(7) 							CONSTRAINT EDIT_CAREER_CAREER_NO_PK 	PRIMARY KEY
, 	EDITOR_ID 		VARCHAR2(30) 						CONSTRAINT EDIT_CAREER_EDTIOR_ID_NN 	NOT NULL
, 	CHANNEL_ID 		VARCHAR2(30) 						CONSTRAINT EDIT_CAREER_CHANNEL_ID_NN	NOT NULL
, 	START_DATE 		DATE 								CONSTRAINT EDIT_CAREER_START_DATE_NN 	NOT NULL
, 	END_DATE 		DATE 								CONSTRAINT EDIT_CAREER_END_DATE_NN 		NOT NULL
, 	IS_APPROVE 		VARCHAR2(5) 	DEFAULT 'FALSE' 	CONSTRAINT EDIT_CAREER_IS_APPROVE_NN 	NOT NULL
, 	IS_REQUEST 		VARCHAR2(5) 	DEFAULT 'FALSE' 	CONSTRAINT EDIT_CAREER_IS_REQUEST_NN 	NOT NULL
, 	CONSTRAINT 	EDIT_CAREER_ID_FK 	FOREIGN KEY 		(EDITOR_ID) 	REFERENCES PORTFOLIO (EDITOR_ID)
);

CREATE TABLE APPLY_EDITOR (
 	APPLY_NO 		NUMBER(7) 					CONSTRAINT APPLY_EDITOR_APPLY_NO_PK 		PRIMARY KEY
, 	RECRUIT_NO 		NUMBER(7) 					CONSTRAINT APPLY_EDITOR_RECRUIT_NO_NN 		NOT NULL
, 	EDITOR_ID 		VARCHAR2(30) 				CONSTRAINT APPLY_EDITOR_ID_NN 				NOT NULL
, 	EDITED_LINK 	VARCHAR2(100) 				CONSTRAINT APPLY_EDITOR_EDITED_LINK_NN 		NOT NULL
, 	EDITOR_MEMO 	VARCHAR2(1000) 	DEFAULT '' 	CONSTRAINT APPLY_EDITOR_EDITOR_MEMO_NN 		NOT NULL
, 	YOUTUBER_MEMO 	VARCHAR2(1000) 	DEFAULT '' 	CONSTRAINT APPLY_EDITOR_YOUTUBER_MEMO_NN 	NOT NULL
, 	CONSTRAINT 	APPLY_EDITOR_RECRUIT_NO_FK 		FOREIGN KEY (RECRUIT_NO) 	REFERENCES RECRUIT_BOARD (RECRUIT_NO)
, 	CONSTRAINT 	APPLY_EDITOR_ID_FK 				FOREIGN KEY (EDITOR_ID) 	REFERENCES USER_EDITOR (EDITOR_ID)
);




CREATE TABLE VIDEO_LINKS (
 	VIDEO_NO 	VARCHAR2(7) 		CONSTRAINT VIDEO_LINKS_VIDEO_NO_PK 		PRIMARY KEY
, 	EDITOR_ID 	VARCHAR2(30) 		CONSTRAINT VIDEO_LINKS_ID_NN 			NOT NULL
, 	VIDEO_LINK 	VARCHAR2(500) 		CONSTRAINT VIDEO_LINKS_VIDEO_LINK_NN 	NOT NULL
, 	PRIORITY 	NUMBER(2) 			CONSTRAINT VIDEO_LINKS_PRIORITY_NN 		NOT NULL
, 	CONSTRAINT 	VIDEO_LINKS_ID_FK 	FOREIGN KEY (EDITOR_ID) REFERENCES PORTFOLIO (EDITOR_ID)
);


CREATE TABLE EDIT_TOOLS_LIST (
 	EDIT_TOOLS_NO 	VARCHAR2(7) 				CONSTRAINT TOOLS_LIST_EDIT_TOOLS_NO_PK 	PRIMARY KEY
, 	EDITOR_ID 		VARCHAR2(30) 				CONSTRAINT TOOLS_LIST_ID_NN 			NOT NULL
, 	EDIT_TOOL 		VARCHAR2(20) 				CONSTRAINT TOOLS_LIST_EDIT_TOOL_NN 		NOT NULL
, 	ETC_DETAILS 	VARCHAR2(30) 	DEFAULT '' 	CONSTRAINT TOOLS_LIST_ETC_DETAILS_NN 	NOT NULL
, 	CONSTRAINT 	EDIT_TOOLS_LIST_ID_FK 			FOREIGN KEY (EDITOR_ID) REFERENCES PORTFOLIO (EDITOR_ID)
, 	CONSTRAINT 	EDIT_TOOLS_LIST_EDIT_TOOL_CK	CHECK (EDIT_TOOL IN('프리미어프로', '애프터이펙트', '베가스', '파이널컷', '파워디렉터', '포토샵', '일러스트레이터', '마야', '블렌더', '기타'))
);


